version: '2'

services:
  client:
    build:
      context: ./
    container_name: client
    ports:
      - 5000:80
    environment:
      - darkSkyAPIKEY=apikeyHere
      - oauthClientId=clientIdHere
    restart: always
